benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 8, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4", ici_size_range: 16, sharding_strategy: "4x1", op_dimension: 0, num_runs: 5} # Shard on dim 0
  - {matrix_dim_range: {start: 8, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4", ici_size_range: 16, sharding_strategy: "4x4", op_dimension: 0, num_runs: 5} # Full sharding
  trace_dir: "../microbenchmarks/all_to_all_v6e_4x4"
  csv_path: "../microbenchmarks/all_to_all_v6e_4x4"
  xlml_metrics_dir: "../microbenchmarks/all_to_all_v6e_4x4"
  xla_dump_dir: "../microbenchmarks/all_to_all_v6e_4x4/hlo_graphs"
