global:
  system: "ironwood"
  warmup_tries: 2
  num_runs: 5
  dtype: "float32"
  xprof_timing: true

benchmarks:
  # Collective communication demonstration
  - name: all_reduce_sum
    mesh_shape: "4x2x2"
    sweep:
      matrix_dim: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]

  - name: all_gather
    mesh_shape: "4x2x2"
    sweep:
      matrix_dim: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]

  - name: all_to_all
    mesh_shape: "4x2x2"
    sweep:
      matrix_dim: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]

  - name: reduce_scatter
    mesh_shape: "4x2x2"
    sweep:
      matrix_dim: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]