global:
  system: "ironwood"
  warmup_tries: 2
  num_runs: 10
  dtype: "float32"
  xprof_timing: true

benchmarks:
  - name: host_to_device
    sweep:
      data_size_mib: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  - name: device_to_host
    sweep:
      data_size_mib: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
