benchmarks:
- benchmark_name: host_device
  num_runs: 20
  benchmark_sweep_params:
  - transfer_type_list: ["pinned_memory", "simple", "pipelined"]
    num_devices_list: [8]
    data_size_mib_list: [1, 16, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
    input_type_list: ["numpy", "jax"]
    dtype_list: ["float32"]
  csv_path: "/tmp/microbenchmarks/host_device_numactl"
